services:
  postgres:
    image: ankane/pgvector
    container_name: postgres_vector
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: banana
      POSTGRES_DB: vectordb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: