services:
  postgres:
    image: ankane/pgvector
    container_name: postgres_vector
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: banana
      POSTGRES_DB: vectordb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs_backend
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=user
      - DB_PASSWORD=banana
      - DB_NAME=postgres
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run start:prod

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vite_frontend
    expose:
      - "80"
    depends_on:
      - backend
    command: npx serve -s dist

volumes:
  postgres_data:
  caddy_data:
  caddy_config: